import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { CategoriesProvider } from "@/context/CategoriesContext";
import { Suspense } from "react";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/header/Header";
import Footer from "@/components/footer";
import HeaderVisibility from "@/components/header/HeaderVisibility";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
          async
        />
      </head>

      <body className={inter.className}>
        <AuthProvider>
          <CategoriesProvider>
            {/* ✅ HEADER GLOBAL */}
            <HeaderVisibility />

            {/* ✅ KONTEN HALAMAN */}
            <Suspense>
              <main className="pt-20">{children}</main>
            </Suspense>

            {/* FOOTER GLOBAL */}
            <Footer />
          </CategoriesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
